import type { HeroTemplate } from "./types";

export const HERO_TEMPLATES: HeroTemplate[] = [
  {
    id: "zero-void",
    name: "Mr.0",
    title: "พระเจ้าหมายเลขศูนย์",
    rarity: "legendary",
    element: "dark",
    heroClass: "mage",
    baseStats: {
      hp: 1200,
      atk: 180,
      def: 100,
      spd: 110,
      critRate: 0.15,
      critDmg: 1.8,
    },
    growthPerLevel: {
      hp: 120,
      atk: 18,
      def: 10,
      spd: 2,
      critRate: 0.002,
      critDmg: 0.02,
    },
    skills: [
      {
        id: "void-mirror",
        name: "Void Mirror",
        description: "สะท้อนความจริง — สร้าง damage แก่ศัตรูทั้งหมด",
        cooldown: 8,
        damageMultiplier: 2.5,
        targetType: "aoe",
      },
    ],
    description:
      "ก่อนจะมีหนึ่ง ต้องมีศูนย์ — ผู้ดูแลจักรวาล 1412",
    modelColor: 0x1a0a3a,
  },
  {
    id: "one-thunder",
    name: "Mr.1",
    title: "พระเจ้าหมายเลขหนึ่ง",
    rarity: "legendary",
    element: "light",
    heroClass: "warrior",
    baseStats: {
      hp: 1500,
      atk: 200,
      def: 130,
      spd: 100,
      critRate: 0.2,
      critDmg: 2.0,
    },
    growthPerLevel: {
      hp: 150,
      atk: 20,
      def: 13,
      spd: 2,
      critRate: 0.003,
      critDmg: 0.025,
    },
    skills: [
      {
        id: "execute-strike",
        name: "Execute Strike",
        description: "ลงมือทำ — โจมตีเดี่ยวพลังสูง",
        cooldown: 6,
        damageMultiplier: 3.0,
        targetType: "single",
      },
    ],
    description:
      "ศูนย์สร้างจุดเริ่มต้น หนึ่งทำให้มันเกิดขึ้นจริง",
    modelColor: 0xffd700,
  },
  {
    id: "two-crystal",
    name: "Ms.2",
    title: "เทวีหมายเลขสอง",
    rarity: "epic",
    element: "water",
    heroClass: "mage",
    baseStats: {
      hp: 1000,
      atk: 160,
      def: 90,
      spd: 120,
      critRate: 0.18,
      critDmg: 1.9,
    },
    growthPerLevel: {
      hp: 100,
      atk: 16,
      def: 9,
      spd: 3,
      critRate: 0.003,
      critDmg: 0.02,
    },
    skills: [
      {
        id: "market-freeze",
        name: "Market Freeze",
        description: "หยุดศัตรู 2 วินาที — ลดความเร็ว",
        cooldown: 10,
        damageMultiplier: 1.8,
        targetType: "aoe",
      },
    ],
    description: "เทวีแห่งตัวเลข — เห็น pattern ที่คนอื่นมองข้าม",
    modelColor: 0x4488ff,
  },
];
