import type { HeroTemplate, Rarity } from "./types";

export function getHeroesByRarity(rarity: Rarity): HeroTemplate[] {
  return HERO_TEMPLATES.filter((h) => h.rarity === rarity);
}

export function getHeroById(id: string): HeroTemplate | undefined {
  return HERO_TEMPLATES.find((h) => h.id === id);
}

export function getHeroesByElement(element: string): HeroTemplate[] {
  return HERO_TEMPLATES.filter((h) => h.element === element);
}

export const HERO_TEMPLATES: HeroTemplate[] = [
  {
    id: "zero-void",
    name: "Mr.0",
    title: "พระเจ้าหมายเลขศูนย์",
    rarity: "legendary",
    element: "dark",
    heroClass: "mage",
    baseStats: {
      hp: 1200,
      atk: 180,
      def: 100,
      spd: 110,
      critRate: 0.15,
      critDmg: 1.8,
    },
    growthPerLevel: {
      hp: 120,
      atk: 18,
      def: 10,
      spd: 2,
      critRate: 0.002,
      critDmg: 0.02,
    },
    skills: [
      {
        id: "void-mirror",
        name: "Void Mirror",
        description: "สะท้อนความจริง — สร้าง damage แก่ศัตรูทั้งหมด",
        cooldown: 8,
        damageMultiplier: 2.5,
        targetType: "aoe",
      },
    ],
    description:
      "ก่อนจะมีหนึ่ง ต้องมีศูนย์ — ผู้ดูแลจักรวาล 1412",
    modelColor: 0x1a0a3a,
  },
  {
    id: "one-thunder",
    name: "Mr.1",
    title: "พระเจ้าหมายเลขหนึ่ง",
    rarity: "legendary",
    element: "light",
    heroClass: "warrior",
    baseStats: {
      hp: 1500,
      atk: 200,
      def: 130,
      spd: 100,
      critRate: 0.2,
      critDmg: 2.0,
    },
    growthPerLevel: {
      hp: 150,
      atk: 20,
      def: 13,
      spd: 2,
      critRate: 0.003,
      critDmg: 0.025,
    },
    skills: [
      {
        id: "execute-strike",
        name: "Execute Strike",
        description: "ลงมือทำ — โจมตีเดี่ยวพลังสูง",
        cooldown: 6,
        damageMultiplier: 3.0,
        targetType: "single",
      },
    ],
    description:
      "ศูนย์สร้างจุดเริ่มต้น หนึ่งทำให้มันเกิดขึ้นจริง",
    modelColor: 0xffd700,
  },
  {
    id: "two-crystal",
    name: "Ms.2",
    title: "เทวีหมายเลขสอง",
    rarity: "epic",
    element: "water",
    heroClass: "mage",
    baseStats: {
      hp: 1000,
      atk: 160,
      def: 90,
      spd: 120,
      critRate: 0.18,
      critDmg: 1.9,
    },
    growthPerLevel: {
      hp: 100,
      atk: 16,
      def: 9,
      spd: 3,
      critRate: 0.003,
      critDmg: 0.02,
    },
    skills: [
      {
        id: "market-freeze",
        name: "Market Freeze",
        description: "หยุดศัตรู 2 วินาที — ลดความเร็ว",
        cooldown: 10,
        damageMultiplier: 1.8,
        targetType: "aoe",
      },
    ],
    description: "เทวีแห่งตัวเลข — เห็น pattern ที่คนอื่นมองข้าม",
    modelColor: 0x4488ff,
  },
  {
    id: "three-bloom",
    name: "Ms.3",
    title: "เทวีหมายเลขสาม",
    rarity: "epic",
    element: "earth",
    heroClass: "healer",
    baseStats: { hp: 1100, atk: 120, def: 110, spd: 105, critRate: 0.12, critDmg: 1.6 },
    growthPerLevel: { hp: 110, atk: 12, def: 11, spd: 2, critRate: 0.002, critDmg: 0.015 },
    skills: [{ id: "garden-of-life", name: "Garden of Life", description: "ฟื้นฟูพลังชีวิตให้ทีมทั้งหมด", cooldown: 9, damageMultiplier: 0, targetType: "aoe" }],
    description: "เทวีแห่งการเติบโต — ดูแลทุกคนให้เบ่งบาน",
    modelColor: 0x44cc88,
  },
  {
    id: "four-aegis",
    name: "Mr.4",
    title: "เทพหมายเลขสี่",
    rarity: "epic",
    element: "fire",
    heroClass: "tank",
    baseStats: { hp: 1800, atk: 100, def: 180, spd: 85, critRate: 0.08, critDmg: 1.5 },
    growthPerLevel: { hp: 180, atk: 10, def: 18, spd: 1, critRate: 0.001, critDmg: 0.01 },
    skills: [{ id: "wellness-ward", name: "Wellness Ward", description: "สร้างเกราะป้องกันให้ทีม — ลด damage รับ 40%", cooldown: 12, damageMultiplier: 0, targetType: "aoe" }],
    description: "โล่ที่แข็งแกร่งที่สุดคือสุขภาพที่ดี",
    modelColor: 0xff6633,
  },
  {
    id: "aria-flameblade",
    name: "Aria",
    title: "Flameheart Knight",
    rarity: "rare",
    element: "fire",
    heroClass: "warrior",
    baseStats: { hp: 900, atk: 140, def: 100, spd: 95, critRate: 0.15, critDmg: 1.7 },
    growthPerLevel: { hp: 90, atk: 14, def: 10, spd: 2, critRate: 0.002, critDmg: 0.018 },
    skills: [{ id: "inferno-slash", name: "Inferno Slash", description: "ฟันเปลวเพลิง — โจมตีเดี่ยวพร้อม burn", cooldown: 5, damageMultiplier: 2.2, targetType: "single" }],
    description: "อัศวินเปลวเพลิงแห่งอาณาจักรที่สาบสูญ",
    modelColor: 0xee4422,
  },
  {
    id: "luna-tideweaver",
    name: "Luna",
    title: "Tidecaller Priestess",
    rarity: "rare",
    element: "water",
    heroClass: "healer",
    baseStats: { hp: 850, atk: 100, def: 85, spd: 100, critRate: 0.1, critDmg: 1.5 },
    growthPerLevel: { hp: 85, atk: 10, def: 8, spd: 2, critRate: 0.002, critDmg: 0.012 },
    skills: [{ id: "tidal-blessing", name: "Tidal Blessing", description: "คลื่นรักษา — ฟื้น HP เป้าเดียวจำนวนมาก", cooldown: 7, damageMultiplier: 0, targetType: "single" }],
    description: "นักบวชแห่งสายน้ำ ผู้รักษาทุกบาดแผล",
    modelColor: 0x66aadd,
  },
  {
    id: "kael-stoneguard",
    name: "Kael",
    title: "Ironwall Sentinel",
    rarity: "uncommon",
    element: "earth",
    heroClass: "tank",
    baseStats: { hp: 1100, atk: 70, def: 130, spd: 75, critRate: 0.05, critDmg: 1.3 },
    growthPerLevel: { hp: 110, atk: 7, def: 13, spd: 1, critRate: 0.001, critDmg: 0.008 },
    skills: [{ id: "earth-wall", name: "Earth Wall", description: "กำแพงหิน — ดึง aggro ศัตรูมาที่ตัวเอง", cooldown: 10, damageMultiplier: 0.5, targetType: "self" }],
    description: "ยามหินแห่งป้อมโบราณ — ไม่มีใครผ่านไปได้",
    modelColor: 0x886644,
  },
  {
    id: "nyx-shadowstep",
    name: "Nyx",
    title: "Shadowstrike Assassin",
    rarity: "uncommon",
    element: "dark",
    heroClass: "archer",
    baseStats: { hp: 600, atk: 120, def: 50, spd: 130, critRate: 0.25, critDmg: 2.0 },
    growthPerLevel: { hp: 60, atk: 12, def: 5, spd: 3, critRate: 0.004, critDmg: 0.025 },
    skills: [{ id: "shadow-barrage", name: "Shadow Barrage", description: "ฝนลูกดอกมืด — โจมตีสุ่ม 3 ครั้ง", cooldown: 6, damageMultiplier: 1.5, targetType: "single" }],
    description: "เงาที่เคลื่อนไหวเร็วกว่าแสง",
    modelColor: 0x2a1a4a,
  },
  {
    id: "sol-lightbringer",
    name: "Sol",
    title: "Dawnbringer Paladin",
    rarity: "common",
    element: "light",
    heroClass: "warrior",
    baseStats: { hp: 700, atk: 90, def: 80, spd: 85, critRate: 0.1, critDmg: 1.5 },
    growthPerLevel: { hp: 70, atk: 9, def: 8, spd: 2, critRate: 0.001, critDmg: 0.01 },
    skills: [{ id: "holy-strike", name: "Holy Strike", description: "แสงศักดิ์สิทธิ์ — โจมตีเดี่ยวพื้นฐาน", cooldown: 4, damageMultiplier: 1.8, targetType: "single" }],
    description: "อัศวินหนุ่มผู้เริ่มต้นเส้นทางแห่งแสง",
    modelColor: 0xeedd88,
  },
  {
    id: "frost-whisper",
    name: "Frost",
    title: "Whisper Mage",
    rarity: "rare",
    element: "water",
    heroClass: "mage",
    baseStats: { hp: 750, atk: 150, def: 65, spd: 110, critRate: 0.18, critDmg: 1.9 },
    growthPerLevel: { hp: 75, atk: 15, def: 6, spd: 2, critRate: 0.003, critDmg: 0.02 },
    skills: [{ id: "blizzard", name: "Blizzard", description: "พายุน้ำแข็ง — โจมตีศัตรูทั้งหมด + ลด SPD", cooldown: 8, damageMultiplier: 2.0, targetType: "aoe" }],
    description: "จอมเวทแห่งน้ำแข็งนิรันดร์ — กระซิบแล้วทุกอย่างหยุดนิ่ง",
    modelColor: 0x88ccff,
  },
  {
    id: "ember-phoenix",
    name: "Ember",
    title: "Phoenix Archer",
    rarity: "rare",
    element: "fire",
    heroClass: "archer",
    baseStats: { hp: 680, atk: 145, def: 55, spd: 120, critRate: 0.2, critDmg: 1.85 },
    growthPerLevel: { hp: 68, atk: 14, def: 5, spd: 3, critRate: 0.003, critDmg: 0.02 },
    skills: [{ id: "phoenix-rain", name: "Phoenix Rain", description: "ฝนลูกศรเพลิง — โจมตีสุ่ม 4 ครั้ง", cooldown: 7, damageMultiplier: 1.6, targetType: "single" }],
    description: "นักธนูที่เกิดใหม่จากเปลวไฟ — ทุกลูกศรคือเปลวฟีนิกซ์",
    modelColor: 0xff6600,
  },
];
